config/routes.rb
Rails.application.routes.draw do
  resources :address_books
  resources :areas
  resources :phone_numbers
  resources :phone_number_groups
  resources :phone_devices
  resources :phone_users

  resources :tech_users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tech_user.rb
class TechUser < ActiveRecord::Base
  has_secure_password
end

app/controllers/tech_users_controller.rb
class TechUsersController < ApplicationController
  before_action :set_tech_user, only: [:show, :edit, :update, :destroy]

  # GET /tech_users
  # GET /tech_users.json
  def index
    @tech_users = TechUser.all
  end

  # GET /tech_users/1
  # GET /tech_users/1.json
  def show
  end

  # GET /tech_users/new
  def new
    @tech_user = TechUser.new
  end

  # GET /tech_users/1/edit
  def edit
  end

  # POST /tech_users
  # POST /tech_users.json
  def create
    @tech_user = TechUser.new(tech_user_params)

    respond_to do |format|
      if @tech_user.save
        format.html { redirect_to @tech_user, notice: 'Tech user was successfully created.' }
        format.json { render :show, status: :created, location: @tech_user }
      else
        format.html { render :new }
        format.json { render json: @tech_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tech_users/1
  # PATCH/PUT /tech_users/1.json
  def update
    respond_to do |format|
      if @tech_user.update(tech_user_params)
        format.html { redirect_to @tech_user, notice: 'Tech user was successfully updated.' }
        format.json { render :show, status: :ok, location: @tech_user }
      else
        format.html { render :edit }
        format.json { render json: @tech_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tech_users/1
  # DELETE /tech_users/1.json
  def destroy
    @tech_user.destroy
    respond_to do |format|
      format.html { redirect_to tech_users_url, notice: 'Tech user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tech_user
      @tech_user = TechUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tech_user_params
      params.require(:tech_user).permit(:name, :login, :password_digest)
    end
end

app/helpers/tech_users_helper.rb
module TechUsersHelper
end

app/views/tech_users/_form.html.haml
= form_for(@tech_user) do |f|
  - if @tech_user.errors.any?
    #error_explanation
      %h2
        = pluralize(@tech_user.errors.count, "error")
        prohibited this tech_user from being saved:
      %ul
        - @tech_user.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :login
    %br/
    = f.text_field :login
  .field
    = f.label :password_digest
    %br/
    = f.text_field :password_digest
  .actions
    = f.submit

app/views/tech_users/edit.html.haml
%h1 Editing Tech User
= render 'form'
= link_to 'Show', @tech_user
|
= link_to 'Back', tech_users_path

app/views/tech_users/index.html.haml
%p#notice= notice
%h1 Listing Tech Users
%table
  %thead
    %tr
      %th Name
      %th Login
      %th Password digest
      %th{:colspan => "3"}
  %tbody
    - @tech_users.each do |tech_user|
      %tr
        %td= tech_user.name
        %td= tech_user.login
        %td= tech_user.password_digest
        %td= link_to 'Show', tech_user
        %td= link_to 'Edit', edit_tech_user_path(tech_user)
        %td= link_to 'Destroy', tech_user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Tech user', new_tech_user_path

app/views/tech_users/new.html.haml
%h1 New Tech User
= render 'form'
= link_to 'Back', tech_users_path

app/views/tech_users/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @tech_user.name
%p
  %strong Login:
  = @tech_user.login
%p
  %strong Password digest:
  = @tech_user.password_digest
= link_to 'Edit', edit_tech_user_path(@tech_user)
|
= link_to 'Back', tech_users_path