config/routes.rb
Rails.application.routes.draw do
  resources :address_books
  resources :areas
  resources :phone_numbers
  resources :phone_number_groups
  resources :phone_devices
  resources :phone_users

  resources :tech_users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/phone_number_group.rb
class PhoneNumberGroup < ActiveRecord::Base
  has_and_belongs_to_many :phone_numbers
  has_and_belongs_to_many :address_books
end

app/controllers/phone_number_groups_controller.rb
class PhoneNumberGroupsController < ApplicationController
  before_action :set_phone_number_group, only: [:show, :edit, :update, :destroy]

  # GET /phone_number_groups
  # GET /phone_number_groups.json
  def index
    @phone_number_groups = PhoneNumberGroup.all
  end

  # GET /phone_number_groups/1
  # GET /phone_number_groups/1.json
  def show
  end

  # GET /phone_number_groups/new
  def new
    @phone_number_group = PhoneNumberGroup.new
  end

  # GET /phone_number_groups/1/edit
  def edit
  end

  # POST /phone_number_groups
  # POST /phone_number_groups.json
  def create
    @phone_number_group = PhoneNumberGroup.new(phone_number_group_params)

    respond_to do |format|
      if @phone_number_group.save
        format.html { redirect_to @phone_number_group, notice: 'Phone number group was successfully created.' }
        format.json { render :show, status: :created, location: @phone_number_group }
      else
        format.html { render :new }
        format.json { render json: @phone_number_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_number_groups/1
  # PATCH/PUT /phone_number_groups/1.json
  def update
    respond_to do |format|
      if @phone_number_group.update(phone_number_group_params)
        format.html { redirect_to @phone_number_group, notice: 'Phone number group was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_number_group }
      else
        format.html { render :edit }
        format.json { render json: @phone_number_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_number_groups/1
  # DELETE /phone_number_groups/1.json
  def destroy
    @phone_number_group.destroy
    respond_to do |format|
      format.html { redirect_to phone_number_groups_url, notice: 'Phone number group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_number_group
      @phone_number_group = PhoneNumberGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_number_group_params
      params.require(:phone_number_group).permit(:name)
    end
end

app/helpers/phone_number_groups_helper.rb
module PhoneNumberGroupsHelper
end

app/views/phone_number_groups/_form.html.haml
= form_for(@phone_number_group) do |f|
  - if @phone_number_group.errors.any?
    #error_explanation
      %h2
        = pluralize(@phone_number_group.errors.count, "error")
        prohibited this phone_number_group from being saved:
      %ul
        - @phone_number_group.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/phone_number_groups/edit.html.haml
%h1 Editing Phone Number Group
= render 'form'
= link_to 'Show', @phone_number_group
|
= link_to 'Back', phone_number_groups_path

app/views/phone_number_groups/index.html.haml
%p#notice= notice
%h1 Listing Phone Number Groups
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @phone_number_groups.each do |phone_number_group|
      %tr
        %td= phone_number_group.name
        %td= link_to 'Show', phone_number_group
        %td= link_to 'Edit', edit_phone_number_group_path(phone_number_group)
        %td= link_to 'Destroy', phone_number_group, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Phone number group', new_phone_number_group_path

app/views/phone_number_groups/new.html.haml
%h1 New Phone Number Group
= render 'form'
= link_to 'Back', phone_number_groups_path

app/views/phone_number_groups/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @phone_number_group.name
= link_to 'Edit', edit_phone_number_group_path(@phone_number_group)
|
= link_to 'Back', phone_number_groups_path