config/routes.rb
Rails.application.routes.draw do
  resources :address_books
  resources :areas
  resources :phone_numbers
  resources :phone_number_groups
  resources :phone_devices
  resources :phone_users

  resources :tech_users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :area_code
  has_and_belongs_to_many :phone_number_groups
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :set_phone_number, only: [:show, :edit, :update, :destroy]

  # GET /phone_numbers
  # GET /phone_numbers.json
  def index
    @phone_numbers = PhoneNumber.all
  end

  # GET /phone_numbers/1
  # GET /phone_numbers/1.json
  def show
  end

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers
  # POST /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number, notice: 'Phone number was successfully created.' }
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :new }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_numbers/1
  # PATCH/PUT /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to @phone_number, notice: 'Phone number was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_number }
      else
        format.html { render :edit }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1
  # DELETE /phone_numbers/1.json
  def destroy
    @phone_number.destroy
    respond_to do |format|
      format.html { redirect_to phone_numbers_url, notice: 'Phone number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_number
      @phone_number = PhoneNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_number_params
      params.require(:phone_number).permit(:phone, :area_code_id)
    end
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/phone_numbers/_form.html.haml
= form_for(@phone_number) do |f|
  - if @phone_number.errors.any?
    #error_explanation
      %h2
        = pluralize(@phone_number.errors.count, "error")
        prohibited this phone_number from being saved:
      %ul
        - @phone_number.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :phone
    %br/
    = f.text_field :phone
  .field
    = f.label :area_code_id
    %br/
    = f.text_field :area_code_id
  .actions
    = f.submit

app/views/phone_numbers/edit.html.haml
%h1 Editing Phone Number
= render 'form'
= link_to 'Show', @phone_number
|
= link_to 'Back', phone_numbers_path

app/views/phone_numbers/index.html.haml
%p#notice= notice
%h1 Listing Phone Numbers
%table
  %thead
    %tr
      %th Phone
      %th Area code
      %th{:colspan => "3"}
  %tbody
    - @phone_numbers.each do |phone_number|
      %tr
        %td= phone_number.phone
        %td= phone_number.area_code
        %td= link_to 'Show', phone_number
        %td= link_to 'Edit', edit_phone_number_path(phone_number)
        %td= link_to 'Destroy', phone_number, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Phone number', new_phone_number_path

app/views/phone_numbers/new.html.haml
%h1 New Phone Number
= render 'form'
= link_to 'Back', phone_numbers_path

app/views/phone_numbers/show.html.haml
%p#notice= notice
%p
  %strong Phone:
  = @phone_number.phone
%p
  %strong Area code:
  = @phone_number.area_code
= link_to 'Edit', edit_phone_number_path(@phone_number)
|
= link_to 'Back', phone_numbers_path