config/routes.rb
Rails.application.routes.draw do
  resources :address_books
  resources :areas
  resources :phone_numbers
  resources :phone_number_groups
  resources :phone_devices
  resources :phone_users

  resources :tech_users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/phone_device.rb
class PhoneDevice < ActiveRecord::Base
  belongs_to :phone_user
  has_many :phone_numbers
  belongs_to :address_book
end

app/controllers/phone_devices_controller.rb
class PhoneDevicesController < ApplicationController
  before_action :set_phone_device, only: [:show, :edit, :update, :destroy]

  # GET /phone_devices
  # GET /phone_devices.json
  def index
    @phone_devices = PhoneDevice.all
  end

  # GET /phone_devices/1
  # GET /phone_devices/1.json
  def show
  end

  # GET /phone_devices/new
  def new
    @phone_device = PhoneDevice.new
  end

  # GET /phone_devices/1/edit
  def edit
  end

  # POST /phone_devices
  # POST /phone_devices.json
  def create
    @phone_device = PhoneDevice.new(phone_device_params)

    respond_to do |format|
      if @phone_device.save
        format.html { redirect_to @phone_device, notice: 'Phone device was successfully created.' }
        format.json { render :show, status: :created, location: @phone_device }
      else
        format.html { render :new }
        format.json { render json: @phone_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_devices/1
  # PATCH/PUT /phone_devices/1.json
  def update
    respond_to do |format|
      if @phone_device.update(phone_device_params)
        format.html { redirect_to @phone_device, notice: 'Phone device was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_device }
      else
        format.html { render :edit }
        format.json { render json: @phone_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_devices/1
  # DELETE /phone_devices/1.json
  def destroy
    @phone_device.destroy
    respond_to do |format|
      format.html { redirect_to phone_devices_url, notice: 'Phone device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_device
      @phone_device = PhoneDevice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_device_params
      params.require(:phone_device).permit(:mac, :model, :phone_user_id)
    end
end

app/helpers/phone_devices_helper.rb
module PhoneDevicesHelper
end

app/views/phone_devices/_form.html.haml
= form_for(@phone_device) do |f|
  - if @phone_device.errors.any?
    #error_explanation
      %h2
        = pluralize(@phone_device.errors.count, "error")
        prohibited this phone_device from being saved:
      %ul
        - @phone_device.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :mac
    %br/
    = f.text_field :mac
  .field
    = f.label :model
    %br/
    = f.text_field :model
  .field
    = f.label :phone_user_id
    %br/
    = f.text_field :phone_user_id
  .actions
    = f.submit

app/views/phone_devices/edit.html.haml
%h1 Editing Phone Device
= render 'form'
= link_to 'Show', @phone_device
|
= link_to 'Back', phone_devices_path

app/views/phone_devices/index.html.haml
%p#notice= notice
%h1 Listing Phone Devices
%table
  %thead
    %tr
      %th Mac
      %th Model
      %th Phone user
      %th{:colspan => "3"}
  %tbody
    - @phone_devices.each do |phone_device|
      %tr
        %td= phone_device.mac
        %td= phone_device.model
        %td= phone_device.phone_user
        %td= link_to 'Show', phone_device
        %td= link_to 'Edit', edit_phone_device_path(phone_device)
        %td= link_to 'Destroy', phone_device, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Phone device', new_phone_device_path

app/views/phone_devices/new.html.haml
%h1 New Phone Device
= render 'form'
= link_to 'Back', phone_devices_path

app/views/phone_devices/show.html.haml
%p#notice= notice
%p
  %strong Mac:
  = @phone_device.mac
%p
  %strong Model:
  = @phone_device.model
%p
  %strong Phone user:
  = @phone_device.phone_user
= link_to 'Edit', edit_phone_device_path(@phone_device)
|
= link_to 'Back', phone_devices_path